package com.mapbox.mapboxsdk.location;

import com.mapbox.mapboxsdk.style.a.a;
import com.mapbox.mapboxsdk.style.layers.Layer;
import com.mapbox.mapboxsdk.style.layers.SymbolLayer;
import com.mapbox.mapboxsdk.style.layers.a;

public final class l {
    static Layer a(String str) {
        SymbolLayer symbolLayer = new SymbolLayer(str, "mapbox-location-source");
        symbolLayer.setProperties(new a("icon-allow-overlap", Boolean.TRUE), new a("icon-ignore-placement", Boolean.TRUE), new a("icon-rotation-alignment", "map"), new a("icon-rotate", com.mapbox.mapboxsdk.style.a.a.a(com.mapbox.mapboxsdk.style.a.a.a(str), (com.mapbox.mapboxsdk.style.a.a) new a.C0310a(Float.valueOf(0.0f)), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-layer", (Object) com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-gps-bearing")), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-stroke-layer", (Object) com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-gps-bearing")), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-shadow", (Object) com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-gps-bearing")), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-bearing-layer", (Object) com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-compass-bearing")))), new com.mapbox.mapboxsdk.style.layers.a("icon-image", com.mapbox.mapboxsdk.style.a.a.a(com.mapbox.mapboxsdk.style.a.a.a(str), com.mapbox.mapboxsdk.style.a.a.a(""), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-layer", (Object) com.mapbox.mapboxsdk.style.a.a.a(com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-location-stale"), com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-foreground-stale-icon"), com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-foreground-icon"))), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-stroke-layer", (Object) com.mapbox.mapboxsdk.style.a.a.a(com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-location-stale"), com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-background-stale-icon"), com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-background-icon"))), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-shadow", (Object) com.mapbox.mapboxsdk.style.a.a.a("mapbox-location-shadow-icon")), com.mapbox.mapboxsdk.style.a.a.a((Object) "mapbox-location-bearing-layer", (Object) com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-shadow-icon")))), new com.mapbox.mapboxsdk.style.layers.a("icon-offset", com.mapbox.mapboxsdk.style.a.a.a(com.mapbox.mapboxsdk.style.a.a.a(str), com.mapbox.mapboxsdk.style.a.a.a((Object[]) new Float[]{Float.valueOf(0.0f), Float.valueOf(0.0f)}), com.mapbox.mapboxsdk.style.a.a.a((Object) com.mapbox.mapboxsdk.style.a.a.a("mapbox-location-layer"), (Object) com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-foreground-icon-offset")), com.mapbox.mapboxsdk.style.a.a.a((Object) com.mapbox.mapboxsdk.style.a.a.a("mapbox-location-shadow"), (Object) com.mapbox.mapboxsdk.style.a.a.b("mapbox-property-shadow-icon-offset")))));
        return symbolLayer;
    }
}
