package com.ss.android.ugc.aweme;

import com.meituan.robust.ChangeQuickRedirect;
import com.meituan.robust.PatchProxy;
import com.ss.android.ugc.aweme.antiaddic.lock.ParentalPlatformManager;
import com.ss.android.ugc.aweme.antiaddic.lock.entity.TimeLockUserSetting;
import com.ss.android.ugc.aweme.antiaddic.lock.ui.AntiAddictionTipActivity;
import com.ss.android.ugc.aweme.antiaddic.lock.ui.TeenagerModeAppealActivity;
import com.ss.android.ugc.aweme.antiaddic.lock.ui.fragment.AntiAddictionTipFragment;
import com.ss.android.ugc.aweme.app.ab;
import com.ss.android.ugc.aweme.app.debug.AbsABActivity;
import com.ss.android.ugc.aweme.base.component.EventActivityComponent;
import com.ss.android.ugc.aweme.base.ui.PoiCardWebPageContainer;
import com.ss.android.ugc.aweme.bizactivity.BizActivityViewModel;
import com.ss.android.ugc.aweme.challenge.ui.AddChallengeFragment;
import com.ss.android.ugc.aweme.challenge.ui.ChallengeDetailFragment;
import com.ss.android.ugc.aweme.challenge.ui.DetailAwemeListFragment;
import com.ss.android.ugc.aweme.choosemusic.fragment.BaseMusicListFragment;
import com.ss.android.ugc.aweme.choosemusic.fragment.ChooseMusicFragment;
import com.ss.android.ugc.aweme.choosemusic.fragment.CollectMusicFragment;
import com.ss.android.ugc.aweme.choosemusic.fragment.NewMusicListFragment;
import com.ss.android.ugc.aweme.choosemusic.fragment.NewMusicTabFragment;
import com.ss.android.ugc.aweme.comment.ui.CommentInputFragment;
import com.ss.android.ugc.aweme.comment.ui.VideoCommentDialogFragment2;
import com.ss.android.ugc.aweme.commerce.billshare.BillShareActivity;
import com.ss.android.ugc.aweme.commerce.challenge.CommerceChallengeFragment;
import com.ss.android.ugc.aweme.commerce.live.HalfScreenRnBox;
import com.ss.android.ugc.aweme.commerce.portfolio.PortfolioActivity;
import com.ss.android.ugc.aweme.commerce.preview.PreviewActivity;
import com.ss.android.ugc.aweme.commercialize.coupon.views.CouponDetailActivity;
import com.ss.android.ugc.aweme.commercialize.loft.LoftPlayFragment;
import com.ss.android.ugc.aweme.commercialize.loft.half.LoftView;
import com.ss.android.ugc.aweme.commercialize.profile.EnterpriseTabFragment;
import com.ss.android.ugc.aweme.commercialize.splash.AwesomeSplashEvent;
import com.ss.android.ugc.aweme.commercialize.views.ProfileQuickShopContainer;
import com.ss.android.ugc.aweme.commercialize.views.cards.AbsAdCardAction;
import com.ss.android.ugc.aweme.commercialize.views.cards.DownloadAdCardAction;
import com.ss.android.ugc.aweme.commercialize.views.cards.FormAdCardAction;
import com.ss.android.ugc.aweme.commercialize.views.cards.TopPageAction;
import com.ss.android.ugc.aweme.commercialize.views.form.AdFormBrowserFragment;
import com.ss.android.ugc.aweme.commercialize.views.form.AdFormMaskFragment;
import com.ss.android.ugc.aweme.commercialize.views.form.BottomFormDialog;
import com.ss.android.ugc.aweme.commercialize.views.form.BottomFormDialogV2;
import com.ss.android.ugc.aweme.crossplatform.activity.MixActivityContainer;
import com.ss.android.ugc.aweme.crossplatform.platform.webview.SingleWebView;
import com.ss.android.ugc.aweme.crossplatform.view.CrossPlatformWebView;
import com.ss.android.ugc.aweme.detail.panel.DetailFragmentPanel;
import com.ss.android.ugc.aweme.detail.ui.DetailFragment;
import com.ss.android.ugc.aweme.detail.ui.DetailPageFragment;
import com.ss.android.ugc.aweme.discover.activity.HotSearchAndDiscoveryActivity;
import com.ss.android.ugc.aweme.discover.alading.SearchAwemeCardViewHolder;
import com.ss.android.ugc.aweme.discover.jedi.SearchJediMixFeedFragment;
import com.ss.android.ugc.aweme.discover.mixfeed.ui.SearchMixFeedFragment;
import com.ss.android.ugc.aweme.discover.model.SearchHistory;
import com.ss.android.ugc.aweme.discover.model.SearchPreventSuicide;
import com.ss.android.ugc.aweme.discover.presenter.SearchUserFragment;
import com.ss.android.ugc.aweme.discover.ui.DiscoverDetailPageFragment;
import com.ss.android.ugc.aweme.discover.ui.HotSearchAndDiscoveryFragment2;
import com.ss.android.ugc.aweme.discover.ui.SearchContainerFragment;
import com.ss.android.ugc.aweme.discover.ui.SearchFragment;
import com.ss.android.ugc.aweme.discover.ui.SearchIntermediateFragment;
import com.ss.android.ugc.aweme.discover.ui.SearchResultFragment;
import com.ss.android.ugc.aweme.face2face.Face2FaceAddFriendActivity;
import com.ss.android.ugc.aweme.favorites.FavoriteListActivity;
import com.ss.android.ugc.aweme.favorites.ui.MusicCollectListFragment;
import com.ss.android.ugc.aweme.favorites.ui.PoiCollectListFragment;
import com.ss.android.ugc.aweme.favorites.ui.StickersCollectListFragment;
import com.ss.android.ugc.aweme.fe.method.BindPhoneMethod;
import com.ss.android.ugc.aweme.fe.method.BroadcastMethod;
import com.ss.android.ugc.aweme.fe.method.CloseHalfDialogBridge;
import com.ss.android.ugc.aweme.fe.method.ZhimaMethod;
import com.ss.android.ugc.aweme.feed.f.ac;
import com.ss.android.ugc.aweme.feed.f.ad;
import com.ss.android.ugc.aweme.feed.f.ae;
import com.ss.android.ugc.aweme.feed.f.ag;
import com.ss.android.ugc.aweme.feed.f.ah;
import com.ss.android.ugc.aweme.feed.f.ai;
import com.ss.android.ugc.aweme.feed.f.aj;
import com.ss.android.ugc.aweme.feed.f.ak;
import com.ss.android.ugc.aweme.feed.f.al;
import com.ss.android.ugc.aweme.feed.f.an;
import com.ss.android.ugc.aweme.feed.f.ao;
import com.ss.android.ugc.aweme.feed.f.ap;
import com.ss.android.ugc.aweme.feed.f.aq;
import com.ss.android.ugc.aweme.feed.f.ar;
import com.ss.android.ugc.aweme.feed.f.j;
import com.ss.android.ugc.aweme.feed.f.k;
import com.ss.android.ugc.aweme.feed.f.l;
import com.ss.android.ugc.aweme.feed.f.n;
import com.ss.android.ugc.aweme.feed.f.p;
import com.ss.android.ugc.aweme.feed.f.q;
import com.ss.android.ugc.aweme.feed.f.r;
import com.ss.android.ugc.aweme.feed.f.t;
import com.ss.android.ugc.aweme.feed.f.v;
import com.ss.android.ugc.aweme.feed.f.w;
import com.ss.android.ugc.aweme.feed.f.y;
import com.ss.android.ugc.aweme.feed.f.z;
import com.ss.android.ugc.aweme.feed.panel.AbsCellFeedFragmentPanel;
import com.ss.android.ugc.aweme.feed.panel.BaseListFragmentPanel;
import com.ss.android.ugc.aweme.feed.panel.CellFeedFragmentPanel;
import com.ss.android.ugc.aweme.feed.panel.FullFeedFragmentPanel;
import com.ss.android.ugc.aweme.feed.panel.u;
import com.ss.android.ugc.aweme.feed.share.command.LiveShareCommandDialog;
import com.ss.android.ugc.aweme.feed.share.command.o;
import com.ss.android.ugc.aweme.feed.ui.BaseCellFeedFragment;
import com.ss.android.ugc.aweme.feed.ui.FeedAvatarView;
import com.ss.android.ugc.aweme.feed.ui.FeedFollowFragment;
import com.ss.android.ugc.aweme.feed.ui.FeedRecommendFragment;
import com.ss.android.ugc.aweme.feed.ui.FeedTimeLineFragment;
import com.ss.android.ugc.aweme.feed.ui.NearByFragment;
import com.ss.android.ugc.aweme.feed.ui.StaggeredNearByFragment;
import com.ss.android.ugc.aweme.feed.ui.bg;
import com.ss.android.ugc.aweme.feed.ui.bo;
import com.ss.android.ugc.aweme.feed.ui.bx;
import com.ss.android.ugc.aweme.feed.ui.seekbar.a.a;
import com.ss.android.ugc.aweme.feed.ui.seekbar.g;
import com.ss.android.ugc.aweme.feedback.SubmitFeedbackActivity;
import com.ss.android.ugc.aweme.follow.FollowCellFeedFragmentPanel;
import com.ss.android.ugc.aweme.follow.FollowTabFragment;
import com.ss.android.ugc.aweme.follow.ui.HeaderViewHolder;
import com.ss.android.ugc.aweme.following.ui.SimpleUserFragment;
import com.ss.android.ugc.aweme.forward.view.BaseAwemeDetailFragment;
import com.ss.android.ugc.aweme.friends.ui.ContactsActivity;
import com.ss.android.ugc.aweme.friends.ui.FindFriendsFragment;
import com.ss.android.ugc.aweme.friends.ui.FindFriendsJediFragment;
import com.ss.android.ugc.aweme.friends.ui.RecommendFriendActivity;
import com.ss.android.ugc.aweme.friends.ui.SummonFriendActivity;
import com.ss.android.ugc.aweme.hotsearch.RankingListActivity;
import com.ss.android.ugc.aweme.live.authentication.LiveBroadcastAuthenticateActivity;
import com.ss.android.ugc.aweme.live.livehostimpl.s;
import com.ss.android.ugc.aweme.live.sdk.chatroom.ui.TTLiveBroadcastView;
import com.ss.android.ugc.aweme.longvideonew.feature.NoOperateModeController;
import com.ss.android.ugc.aweme.main.CaptchaLifeCycleObserver;
import com.ss.android.ugc.aweme.main.HomeFragment;
import com.ss.android.ugc.aweme.main.MainActivity;
import com.ss.android.ugc.aweme.main.MainFragment;
import com.ss.android.ugc.aweme.main.MainPageFragment;
import com.ss.android.ugc.aweme.main.base.MainBottomTabView;
import com.ss.android.ugc.aweme.main.follow.LiveBroadcastWarn;
import com.ss.android.ugc.aweme.main.guide.FriendTabGuideDialogFragment;
import com.ss.android.ugc.aweme.music.OriginMusicListFragment;
import com.ss.android.ugc.aweme.music.a.i;
import com.ss.android.ugc.aweme.music.ui.MusicDetailFragment;
import com.ss.android.ugc.aweme.music.ui.MusicDetailFragmentOld;
import com.ss.android.ugc.aweme.music.ui.MusicListFragment;
import com.ss.android.ugc.aweme.music.ui.MusicTabListFragment;
import com.ss.android.ugc.aweme.newfollow.ui.FollowFeedFragment;
import com.ss.android.ugc.aweme.newfollow.ui.FriendTabFragment;
import com.ss.android.ugc.aweme.newfollow.ui.FullScreenFollowFeedIn2TabFragment;
import com.ss.android.ugc.aweme.newfollow.vh.BaseFollowViewHolder;
import com.ss.android.ugc.aweme.newfollow.vh.FollowVideoViewHolder;
import com.ss.android.ugc.aweme.newfollow.vh.InsFollowLiveViewHolderA;
import com.ss.android.ugc.aweme.notification.FansDetailActivity;
import com.ss.android.ugc.aweme.notification.NotificationDetailActivity;
import com.ss.android.ugc.aweme.o.f;
import com.ss.android.ugc.aweme.poi.nearby.ui.PoiSameCityActivity;
import com.ss.android.ugc.aweme.poi.search.POISearchDialog;
import com.ss.android.ugc.aweme.poi.ui.AbsSlidablePoiAwemeFeedFragment;
import com.ss.android.ugc.aweme.poi.ui.PoiDetailActivity;
import com.ss.android.ugc.aweme.poi.ui.h;
import com.ss.android.ugc.aweme.profile.SlideSettingPageFragment;
import com.ss.android.ugc.aweme.profile.model.FollowStatus;
import com.ss.android.ugc.aweme.profile.model.InviteStatus;
import com.ss.android.ugc.aweme.profile.model.WatchStatus;
import com.ss.android.ugc.aweme.profile.ui.AwemeListFragment;
import com.ss.android.ugc.aweme.profile.ui.BaseDTProfileFragment;
import com.ss.android.ugc.aweme.profile.ui.BaseProfileFragment;
import com.ss.android.ugc.aweme.profile.ui.MusAbsProfileFragment;
import com.ss.android.ugc.aweme.profile.ui.MusMyProfileFragment;
import com.ss.android.ugc.aweme.profile.ui.MusUserProfileFragment;
import com.ss.android.ugc.aweme.profile.ui.MyProfileFragment;
import com.ss.android.ugc.aweme.profile.ui.ProfileMoreFragment;
import com.ss.android.ugc.aweme.profile.ui.UserProfileFragment;
import com.ss.android.ugc.aweme.profile.ui.dh;
import com.ss.android.ugc.aweme.promote.PromoteProgramDialog;
import com.ss.android.ugc.aweme.qrcode.v2.ScanQRCodeActivityV2;
import com.ss.android.ugc.aweme.setting.ui.DigitalWellbeingActivity;
import com.ss.android.ugc.aweme.setting.ui.SettingAccountAndSafetyActivity;
import com.ss.android.ugc.aweme.setting.ui.SettingNewVersionActivity;
import com.ss.android.ugc.aweme.setting.ui.af;
import com.ss.android.ugc.aweme.share.bs;
import com.ss.android.ugc.aweme.shortvideo.adapter.PublishSyncItemView;
import com.ss.android.ugc.aweme.shortvideo.adapter.PublishSyncViewHolder;
import com.ss.android.ugc.aweme.shortvideo.f.f;
import com.ss.android.ugc.aweme.shortvideo.sticker.infoSticker.interact.consume.widget.InteractStickerWidget;
import com.ss.android.ugc.aweme.shortvideo.ui.ChooseMusicActivity;
import com.ss.android.ugc.aweme.sticker.prop.fragment.StickerPropDetailFragment;
import com.ss.android.ugc.aweme.ttplatformapi.TtAuthorizeActivity;
import com.ss.android.ugc.aweme.web.jsbridge.LoginMethod;
import com.ss.android.ugc.aweme.web.jsbridge.am;
import java.util.HashMap;
import java.util.Map;
import org.greenrobot.eventbus.ThreadMode;
import org.greenrobot.eventbus.a.b;
import org.greenrobot.eventbus.a.c;
import org.greenrobot.eventbus.a.d;
import org.greenrobot.eventbus.a.e;
import org.greenrobot.eventbus.m;

public final class x implements d {

    /* renamed from: a  reason: collision with root package name */
    public static ChangeQuickRedirect f50732a;

    /* renamed from: b  reason: collision with root package name */
    private static final Map<Class<?>, c> f50733b = new HashMap();

    static {
        a((c) new b(PoiSameCityActivity.class, true, new e[]{new e("onChangeCityEvent", com.ss.android.ugc.aweme.feed.f.d.class)}));
        a((c) new b(MusicTabListFragment.class, true, new e[]{new e("onCheckLoginStateEvent", com.ss.android.ugc.aweme.music.a.b.class), new e("onSwitchMusicFragmentEvent", i.class), new e("onMusicCollectEvent", com.ss.android.ugc.aweme.music.a.e.class)}));
        a((c) new b(com.ss.android.ugc.aweme.feed.ui.seekbar.a.c.class, true, new e[]{new e("onFullFeedFragmentPanelOnPageScrollEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.b.class), new e("onVideoProgressVolumeKeyEvent", g.class), new e("onFullFeedFragmentLifeCycleEvent", a.class), new e("onFullFeedVideoChangeEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.a.class), new e("onPlayerControllerRenderFirstFrameEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.c.class), new e("onPlayerControllerVideoStatusEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.e.class), new e("onPlayerControllerVideoPlayProgressChange", com.ss.android.ugc.aweme.feed.ui.seekbar.d.class)}));
        a((c) new b(PoiCardWebPageContainer.class, true, new e[]{new e("onEvent", AbsAdCardAction.d.class)}));
        a((c) new b(ContactsActivity.class, true, new e[]{new e("onFollowStatusUpdate", FollowStatus.class), new e("onInviteStatusUpdate", InviteStatus.class)}));
        a((c) new b(ParentalPlatformManager.class, true, new e[]{new e("onParentalModeChanged", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(com.ss.android.ugc.aweme.freeflowcard.freeflowmember.a.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.common.net.a.class)}));
        a((c) new b(DiscoverDetailPageFragment.class, true, new e[]{new e("onVideoPlayerEvent", f.class), new e("onUserFollowEvent", FollowStatus.class)}));
        a((c) new b(com.ss.android.ugc.aweme.message.d.f.class, true, new e[]{new e("onEvent", com.ss.android.websocket.b.b.d.class), new e("onEvent", com.ss.android.websocket.b.b.g.class), new e("onEvent", com.ss.android.websocket.b.b.a.class), new e("onEvent", com.ss.android.websocket.b.b.b.class), new e("onEvent", com.ss.android.websocket.b.b.c.class), new e("onEvent", com.ss.android.ugc.aweme.qrcode.a.a.class)}));
        a((c) new b(HotSearchAndDiscoveryActivity.class, true, new e[]{new e("onSearchHistoryEvent", SearchHistory.class)}));
        a((c) new b(NotificationDetailActivity.class, true, new e[]{new e("onProfileFollowEvent", com.ss.android.ugc.aweme.challenge.a.d.class)}));
        a((c) new b(SearchJediMixFeedFragment.class, true, new e[]{new e("onVideoEvent", ar.class)}));
        a((c) new b(BottomFormDialog.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.commercialize.b.b.class)}));
        a((c) new b(DetailPageFragment.class, true, new e[]{new e("onDislikeAwemeEvent", com.ss.android.ugc.aweme.feed.f.i.class), new e("onCommentShowEvent", com.ss.android.ugc.aweme.comment.b.d.class), new e("onScrollToDetailEvent", ah.class), new e("onScaleToCloseDetailEvent", ag.class), new e("onMobEnterFromEvent", w.class), new e("onMobRequestIdEvent", com.ss.android.ugc.aweme.feed.f.x.class), new e("onFeedFetchEvent", q.class), new e("onBlockUserEvent", com.ss.android.ugc.aweme.feed.f.b.class)}));
        a((c) new b(DownloadAdCardAction.class, true, new e[]{new e("onEvent", AbsAdCardAction.b.class)}));
        a((c) new b(PublishSyncItemView.class, true, new e[]{new e("onPublishSyncEvent", com.ss.android.ugc.aweme.shortvideo.adapter.a.class)}));
        a((c) new b(com.ss.android.ugc.aweme.newfollow.ui.c.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.forward.c.a.class), new e("onAwesomeSplashEvent", AwesomeSplashEvent.class)}));
        a((c) new b(com.ss.android.ugc.aweme.feed.adapter.f.class, true, new e[]{new e("onFollowLiveStatusChange", com.bytedance.android.live.base.a.a.class)}));
        e eVar = new e("onMusicCollectEvent", com.ss.android.ugc.aweme.music.a.e.class, ThreadMode.POSTING, 0, true);
        a((c) new b(BaseMusicListFragment.class, true, new e[]{eVar}));
        a((c) new b(FollowTabFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.main.c.b.class), new e("onResizeStatusViewEvent", com.ss.android.ugc.aweme.follow.b.b.class), new e("onFollowStatusUpdate", FollowStatus.class)}));
        a((c) new b(com.ss.android.ugc.aweme.profile.ui.header.a.class, true, new e[]{new e("onJsBroacastReceiver", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(CellFeedFragmentPanel.class, true, new e[]{new e("onDynamicEvent", com.ss.android.ugc.aweme.challenge.a.c.class)}));
        a((c) new b(LoftPlayFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.commercialize.loft.a.a.class)}));
        a((c) new b(BaseCellFeedFragment.class, true, new e[]{new e("onMainSwipeRefreshABChangedEvent", com.ss.android.ugc.aweme.main.c.c.class)}));
        a((c) new b(com.ss.android.ugc.aweme.live.hostbusiness.b.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.live.a.a.class), new e("onEvent", com.ss.android.ugc.aweme.live.a.b.class), new e("onEvent", com.ss.android.ugc.aweme.live.a.c.class)}));
        a((c) new b(s.b.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.base.a.b.class), new e("onEvent", com.ss.android.ugc.aweme.base.a.g.class)}));
        a((c) new b(MainActivity.class, true, new e[]{new e("onPublishMessage", com.ss.android.ugc.aweme.story.model.b.class, ThreadMode.MAIN), new e("onUserLoginStateChange", com.ss.android.ugc.aweme.base.a.f.class), new e("onMobEnterFromEvent", w.class), new e("onMobRequestIdEvent", com.ss.android.ugc.aweme.feed.f.x.class), new e("onCommentShowEvent", com.ss.android.ugc.aweme.comment.b.d.class), new e("onScrollToHotSearchEvent", ai.class), new e("onWebSocketEvent", com.ss.android.websocket.b.a.f.class), new e("onSlideSwitchLayoutInMainActivityConsumer", ap.class), new e("onScrollToDetailEvent", ah.class), new e("onMainActivityConsumer", v.class), new e("onVideoPageChangeEvent", ac.class), new e("onScrollToProfileEvent", aj.class), new e("onUserBannedEvent", com.ss.android.ugc.aweme.base.a.d.class, ThreadMode.MAIN), new e("onAwesomeSplashEvent", AwesomeSplashEvent.class), new e("onCommentDialogEvent", com.ss.android.ugc.aweme.feed.f.f.class), new e("onSubscriberExceptionEvent", m.class), new e("onNextVideo", f.class, ThreadMode.MAIN)}));
        a((c) new b(FollowCellFeedFragmentPanel.class, true, new e[]{new e("onDeleteItemEvent", com.ss.android.ugc.aweme.newfollow.c.a.class), new e("onVideoEvent", ar.class), new e("onFollowStatusUpdate", FollowStatus.class), new e("onDynamicEvent", com.ss.android.ugc.aweme.challenge.a.c.class)}));
        a((c) new b(FullFeedFragmentPanel.class, true, new e[]{new e("onDislikeAwemeEvent", com.ss.android.ugc.aweme.feed.f.i.class), new e("onVideoCleanModeEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.a.b.class), new e("onMainSwipeRefreshABChangedEvent", com.ss.android.ugc.aweme.main.c.c.class), new e("onCommentDialogEvent", com.ss.android.ugc.aweme.feed.f.f.class), new e("onShareDialogEvent", ak.class), new e("onDeleteAwemeEvent", com.ss.android.ugc.aweme.feed.f.g.class)}));
        a((c) new b(am.class, true, new e[]{new e("onVerifyEvent", com.ss.android.ugc.aweme.verify.a.class)}));
        a((c) new b(AbsABActivity.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.setting.a.a.class)}));
        a((c) new b(FindFriendsJediFragment.class, true, new e[]{new e("onNotificationIndicatorEvent", com.ss.android.ugc.aweme.message.b.c.class), new e("onHidePerfectInfoGuideEvent", com.ss.android.ugc.aweme.profile.a.c.class)}));
        e eVar2 = new e("onSettingSyncDone", com.ss.android.ugc.aweme.setting.a.d.class, ThreadMode.POSTING, 0, true);
        a((c) new b(FeedRecommendFragment.class, true, new e[]{eVar2, new e("onFeedFetchEvent", q.class)}));
        a((c) new b(com.ss.android.ugc.aweme.audio.c.class, true, new e[]{new e("onVideoStatusChanged", f.class, ThreadMode.MAIN)}));
        a((c) new b(BaseProfileFragment.class, true, new e[]{new e("onLogoutEvent", com.ss.android.ugc.aweme.app.d.g.class), new e("onNeedScrollToTop", dh.class)}));
        a((c) new b(bg.class, true, new e[]{new e("onCommentEvent", com.ss.android.ugc.aweme.comment.b.a.class), new e("onVideoEvent", ar.class)}));
        a((c) new b(com.ss.android.ugc.aweme.flow.manager.impl.d.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.common.net.a.class)}));
        a((c) new b(FeedAvatarView.class, true, new e[]{new e("onFollowEvent", FollowStatus.class)}));
        a((c) new b(CommentInputFragment.class, true, new e[]{new e("onCommentEvent", com.ss.android.ugc.aweme.comment.b.a.class), new e("onDislikeAwemeEvent", com.ss.android.ugc.aweme.feed.f.i.class), new e("onEvent", com.ss.android.ugc.aweme.forward.c.a.class)}));
        a((c) new b(ChooseMusicActivity.class, true, new e[]{new e("onHideCancelButtonEvent", com.ss.android.ugc.aweme.music.a.c.class)}));
        a((c) new b(BaseAwemeDetailFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.forward.c.a.class), new e("onReportCommentEvent", BroadcastMethod.a.class)}));
        a((c) new b(FeedTimeLineFragment.class, true, new e[]{new e("onMainSwipeRefreshABChangedEvent", com.ss.android.ugc.aweme.main.c.c.class)}));
        a((c) new b(DetailAwemeListFragment.class, true, new e[]{new e("onDynamicEvent", com.ss.android.ugc.aweme.challenge.a.c.class), new e("onFollowStatusUpdate", FollowStatus.class), new e("onVideoEvent", ar.class), new e("onBlockUserEvent", com.ss.android.ugc.aweme.feed.f.b.class)}));
        a((c) new b(MusicDetailFragmentOld.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onVideoEvent", ar.class)}));
        a((c) new b(h.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.forward.c.a.class)}));
        a((c) new b(MixActivityContainer.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onEvent", com.ss.android.ugc.aweme.crossplatform.a.a.class)}));
        e eVar3 = new e("onSettingSyncDone", com.ss.android.ugc.aweme.setting.a.d.class, ThreadMode.POSTING, 0, true);
        e eVar4 = new e("onQueryUserFinishedEvent", com.ss.android.ugc.aweme.base.a.a.class, ThreadMode.POSTING, 0, true);
        e eVar5 = new e("requestPermission", com.ss.android.ugc.aweme.main.dialogmanager.c.class, ThreadMode.POSTING, 0, true);
        a((c) new b(MainPageFragment.class, true, new e[]{new e("onMobEnterFromEvent", w.class), new e("onAwesomeSplashEvent", AwesomeSplashEvent.class), new e("onBottomTabTransParentEvent", com.ss.android.ugc.aweme.feed.f.c.class), eVar3, new e("onScrolledToProfileTab", com.ss.android.ugc.aweme.share.model.b.class), new e("switchToFriendTab", com.ss.android.ugc.aweme.main.c.f.class), new e("onChangeCityEvent", com.ss.android.ugc.aweme.feed.f.d.class), new e("onFollowTabBubbleGuideEvent", t.class), new e("onProfileFollowEvent", com.ss.android.ugc.aweme.challenge.a.d.class), new e("onFollowTabNoticeEvent", com.ss.android.ugc.aweme.message.b.a.class), new e("onNotificationIndicatorEvent", com.ss.android.ugc.aweme.message.b.c.class), new e("onFeedbackEvent", com.ss.android.ugc.aweme.feedback.c.class), new e("onNavigateToTab", com.ss.android.ugc.aweme.message.b.b.class), new e("onRefreshEndEvent", ae.class), eVar4, new e("onVideoPageChangeEvent", ac.class), new e("onScroll2StoryPublishPage", com.ss.android.ugc.aweme.main.c.d.class), new e("onCloseStoryRecordEvent", com.ss.android.ugc.aweme.main.c.a.class), new e("onCommentDialogEvent", com.ss.android.ugc.aweme.feed.f.f.class), new e("onShootEvent", com.ss.android.ugc.aweme.feed.f.am.class), new e("onFollowInRecommendEvent", com.ss.android.ugc.aweme.feed.f.s.class), new e("showDialog", com.ss.android.ugc.aweme.main.dialogmanager.a.class), eVar5, new e("onDislikeAwemeEvent", com.ss.android.ugc.aweme.feed.f.i.class), new e("onCommerceDialogEvent", an.class)}));
        a((c) new b(bs.class, true, new e[]{new e("onPublishSyncEvent", com.ss.android.ugc.aweme.shortvideo.adapter.a.class)}));
        a((c) new b(LiveShareCommandDialog.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.live.a.a.class)}));
        a((c) new b(EnterpriseTabFragment.class, true, new e[]{new e("top", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(PoiCollectListFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.music.a.h.class)}));
        a((c) new b(SearchIntermediateFragment.class, true, new e[]{new e("onSearchHistoryChangedEvent", com.ss.android.ugc.aweme.discover.a.f.class)}));
        a((c) new b(f.h.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.live.authentication.model.a.class, ThreadMode.MAIN)}));
        a((c) new b(BaseFollowViewHolder.class, true, new e[]{new e("onForwardResultEvent", com.ss.android.ugc.aweme.forward.c.a.class)}));
        a((c) new b(FindFriendsFragment.class, true, new e[]{new e("onNotificationIndicatorEvent", com.ss.android.ugc.aweme.message.b.c.class), new e("onHidePerfectInfoGuideEvent", com.ss.android.ugc.aweme.profile.a.c.class)}));
        a((c) new b(DetailFragmentPanel.class, true, new e[]{new e("onDislikeAwemeEvent", com.ss.android.ugc.aweme.feed.f.i.class), new e("onDeleteAwemeEvent", com.ss.android.ugc.aweme.feed.f.g.class), new e("onHideCommentInputFragmentEvent", com.ss.android.ugc.aweme.commercialize.b.f.class), new e("onCommentDialogEvent", com.ss.android.ugc.aweme.feed.f.f.class), new e("onCommentEvent", com.ss.android.ugc.aweme.comment.b.a.class), new e("onDuetSettingEvent", com.ss.android.ugc.aweme.shortvideo.f.c.class), new e("onCommerceDialogEvent", an.class), new e("onVideoCleanModeEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.detailvideo.a.class)}));
        a((c) new b(com.ss.android.ugc.aweme.message.d.g.class, true, new e[]{new e("onCloseWs", com.ss.android.websocket.b.a.a.class), new e("onOpenWs", com.ss.android.websocket.b.a.b.class), new e("onSendWs", com.ss.android.websocket.b.a.d.class)}));
        a((c) new b(HeaderViewHolder.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.main.story.g.class)}));
        a((c) new b(ProfileMoreFragment.class, true, new e[]{new e("onFollowStatusUpdate", FollowStatus.class), new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class)}));
        a((c) new b(AntiAddictionTipActivity.class, true, new e[]{new e("onCloseAntiAddictionEvent", com.ss.android.ugc.aweme.antiaddic.b.a.class, ThreadMode.MAIN)}));
        a((c) new b(MusicDetailFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onVideoEvent", ar.class)}));
        a((c) new b(SearchFragment.class, true, new e[]{new e("onSearchAfterLogin", com.ss.android.ugc.aweme.discover.a.d.class)}));
        a((c) new b(MusUserProfileFragment.class, true, new e[]{new e("onUpdateUserEvent", com.ss.android.ugc.aweme.base.a.b.class), new e("onMobRequestIdEvent", com.ss.android.ugc.aweme.feed.f.x.class), new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onFollowStatusUpdate", FollowStatus.class), new e("onWatchStatusEvent", WatchStatus.class)}));
        a((c) new b(com.ss.android.ugc.aweme.newfollow.f.a.class, true, new e[]{new e("onDeleteItemEvent", com.ss.android.ugc.aweme.newfollow.c.a.class)}));
        a((c) new b(ScanQRCodeActivityV2.class, true, new e[]{new e("onNetStateChangeEvent", com.ss.android.ugc.aweme.qrcode.a.a.class)}));
        a((c) new b(bx.class, true, new e[]{new e("onVideoPlayerStatusUpdate", com.ss.android.ugc.aweme.shortvideo.f.f.class), new e("onAwesomeSplashEvent", AwesomeSplashEvent.class), new e("onShareEndEvent", al.class), new e("onStopTrackingTouchEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.f.class), new e("onPlayerControllerVideoPlayProgressEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.d.class), new e("onVideoCleanModeEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.a.b.class), new e("VideoSeekBarHideEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.h.class)}));
        a((c) new b(CrossPlatformWebView.class, true, new e[]{new e("onJsBroadcastEvent", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(TeenagerModeAppealActivity.class, true, new e[]{new e("onCloseAntiAddictionEvent", com.ss.android.ugc.aweme.antiaddic.b.a.class, ThreadMode.MAIN)}));
        a((c) new b(SearchUserFragment.class, true, new e[]{new e("onFollowStatus", FollowStatus.class), new e("onProfileFollowEvent", com.ss.android.ugc.aweme.challenge.a.d.class)}));
        a((c) new b(OriginMusicListFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.music.a.g.class)}));
        a((c) new b(com.ss.android.ugc.aweme.main.a.b.class, true, new e[]{new e("onEventMainThread", com.ss.android.ugc.aweme.main.a.a.class, ThreadMode.MAIN)}));
        a((c) new b(BaseListFragmentPanel.class, true, new e[]{new e("onEveningEvent", p.class), new e("onPrivateModelEvent", ad.class), new e("onFakeLabelEvent", com.ss.android.ugc.aweme.comment.b.c.class), new e("onNetStateChangeEvent", com.ss.android.ugc.aweme.qrcode.a.a.class), new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onVoteEvent", com.ss.android.ugc.aweme.shortvideo.sticker.infoSticker.interact.consume.b.a.class), new e("onAutoPlayEvent", com.ss.android.ugc.aweme.feed.f.a.class), new e("onDeleteAwemeEventOnBase", com.ss.android.ugc.aweme.feed.f.g.class), new e("onCleanModeChangedEvent", com.ss.android.ugc.aweme.main.b.a.class), new e("tryResumePlayEvent", aq.class), new e("onScroll2StoryPublishPage", com.ss.android.ugc.aweme.main.c.d.class), new e("onLoginPageShowEvent", com.ss.android.ugc.aweme.login.a.c.class), new e("onLoginPageCloseEvent", com.ss.android.ugc.aweme.login.a.b.class), new e("onEvent", FollowStatus.class), new e("onPauseVideoEvent", com.ss.android.ugc.aweme.commerce.service.f.d.class), new e("onRestrictEvent", com.ss.android.ugc.aweme.setting.a.c.class), new e("onBottomTabClicked", com.ss.android.ugc.aweme.share.w.class), new e("onVideoPlayerEvent", com.ss.android.ugc.aweme.shortvideo.f.f.class), new e("onVideoEvent", ar.class), new e("onScrollToProfileGuideEvent", com.ss.android.ugc.aweme.detail.c.b.class), new e("onFeedAdClickFormEvent", com.ss.android.ugc.aweme.commercialize.b.e.class), new e("onFeedAdClickCouponEvent", com.ss.android.ugc.aweme.commercialize.b.d.class), new e("onEvnet", n.class), new e("onEvent", AbsAdCardAction.c.class), new e("onEvent", AbsAdCardAction.a.class), new e("onDismissEnterMusicGuideEvent", j.class), new e("onDismissEnterMusicGuideEvent", com.ss.android.ugc.aweme.main.a.a.class), new e("onAdFeedRefreshEvent", com.ss.android.ugc.aweme.commercialize.b.a.class), new e("onAwesomeSplashEvent", AwesomeSplashEvent.class), new e("onScrolledToProfileTab", com.ss.android.ugc.aweme.share.model.b.class), new e("onScrolledToHomePageTab", com.ss.android.ugc.aweme.share.model.a.class), new e("onReceiveDislikeAwemeEvent", com.ss.android.ugc.aweme.feed.f.i.class)}));
        a((c) new b(FavoriteListActivity.class, true, new e[]{new e("onVideoEvent", ar.class)}));
        a((c) new b(DigitalWellbeingActivity.class, true, new e[]{new e("onEvent", TimeLockUserSetting.class, ThreadMode.MAIN)}));
        a((c) new b(o.class, true, new e[]{new e("onAwesomeSplashEvent", AwesomeSplashEvent.class)}));
        a((c) new b(FollowFeedFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onStoryPublishAnimEnd", com.ss.android.ugc.aweme.main.c.e.class), new e("onVoteEvent", com.ss.android.ugc.aweme.shortvideo.sticker.infoSticker.interact.consume.b.a.class), new e("onLiveRoomScrollEvent", com.ss.android.ugc.aweme.live.model.e.class)}));
        a((c) new b(TTLiveBroadcastView.class, true, new e[]{new e("onEvnet", com.ss.android.ugc.aweme.live.authentication.model.a.class, ThreadMode.MAIN), new e("onFilterChange", com.ss.android.ugc.aweme.live.model.d.class), new e("onCameraReverse", com.ss.android.ugc.aweme.story.live.a.class)}));
        a((c) new b(MusMyProfileFragment.class, true, new e[]{new e("onMyEnterpriseProfileEvent", com.ss.android.ugc.aweme.commercialize.b.g.class), new e("onFollowStatusUpdate", FollowStatus.class), new e("onSaveUserDataEvent", com.ss.android.ugc.aweme.profile.a.d.class), new e("onUpdateUserEvent", com.ss.android.ugc.aweme.base.a.b.class), new e("onUpdateUserSuccessEvent", com.ss.android.ugc.aweme.base.a.c.class), new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onVideoEvent", ar.class), new e("onHidePerfectInfoGuideEvent", com.ss.android.ugc.aweme.profile.a.c.class), new e("onAuthRefreshEvent", com.ss.android.ugc.aweme.commerce.service.f.a.class)}));
        a((c) new b(AbsSlidablePoiAwemeFeedFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.poi.b.a.class), new e("onEvent", com.ss.android.ugc.aweme.poi.b.b.class), new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onEvent", com.ss.android.ugc.aweme.music.a.h.class)}));
        e eVar6 = new e("onQueryUserFinishedEvent", com.ss.android.ugc.aweme.base.a.a.class, ThreadMode.POSTING, 0, true);
        a((c) new b(ab.class, true, new e[]{eVar6}));
        a((c) new b(BillShareActivity.class, true, new e[]{new e("onEvent", ar.class)}));
        a((c) new b(SimpleUserFragment.class, true, new e[]{new e("onFollowStatusUpdate", FollowStatus.class)}));
        a((c) new b(HalfScreenRnBox.class, true, new e[]{new e("closeHalfDialog", CloseHalfDialogBridge.a.class, ThreadMode.MAIN), new e("business", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(AntiAddictionTipFragment.class, true, new e[]{new e("onCloseAntiAddictionEvent", com.ss.android.ugc.aweme.antiaddic.b.a.class, ThreadMode.MAIN)}));
        a((c) new b(ChallengeDetailFragment.class, true, new e[]{new e("onVideoEvent", ar.class), new e("onMusicCollectEvent", com.ss.android.ugc.aweme.music.a.e.class)}));
        a((c) new b(FansDetailActivity.class, true, new e[]{new e("onProfileFollowEvent", com.ss.android.ugc.aweme.challenge.a.d.class)}));
        a((c) new b(DetailFragment.class, true, new e[]{new e("receiveJumpToRecord", com.ss.android.ugc.aweme.shortvideo.sticker.unlock.f.class), new e("onScrollToProfileEvent", aj.class), new e("onEvent", com.ss.android.ugc.aweme.detail.ui.a.class)}));
        a((c) new b(RecommendFriendActivity.class, true, new e[]{new e("onProfileFollowEvent", com.ss.android.ugc.aweme.challenge.a.d.class)}));
        a((c) new b(s.a.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.challenge.a.d.class)}));
        a((c) new b(SearchMixFeedFragment.class, true, new e[]{new e("onSearchAfterLogin", com.ss.android.ugc.aweme.discover.a.d.class)}));
        a((c) new b(MainBottomTabView.class, true, new e[]{new e("onAwesomeSplashEvent", AwesomeSplashEvent.class)}));
        a((c) new b(com.ss.android.ugc.aweme.challenge.ui.header.a.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class)}));
        a((c) new b(InteractStickerWidget.class, true, new e[]{new e("onDissmissInteractWindow", k.class)}));
        a((c) new b(com.ss.android.ugc.aweme.rocket.k.class, true, new e[]{new e("onEvent", com.ss.android.websocket.b.b.c.class), new e("onEvent", com.ss.android.websocket.b.b.g.class)}));
        e eVar7 = new e("onMobMusicTypeEvent", com.ss.android.ugc.aweme.music.a.d.class, ThreadMode.POSTING, 0, true);
        e eVar8 = new e("onMusicCollectEvent", com.ss.android.ugc.aweme.music.a.e.class, ThreadMode.POSTING, 0, true);
        a((c) new b(NewMusicListFragment.class, true, new e[]{eVar7, eVar8}));
        a((c) new b(BindPhoneMethod.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.account.e.a.class)}));
        a((c) new b(StickerPropDetailFragment.class, true, new e[]{new e("receiveJumpMessage", com.ss.android.ugc.aweme.shortvideo.sticker.unlock.e.class)}));
        a((c) new b(AwemeListFragment.class, true, new e[]{new e("onMobRequestIdEvent", com.ss.android.ugc.aweme.feed.f.x.class), new e("onFollowStatusUpdate", FollowStatus.class), new e("onDynamicEvent", com.ss.android.ugc.aweme.challenge.a.c.class), new e("onPrivateModelEvent", ad.class), new e("onUpdateWhoCanSeeMyLikeListModeEvent", af.class, ThreadMode.MAIN), new e("onPublishStatusUpdate", com.ss.android.ugc.aweme.shortvideo.f.e.class), new e("onVideoEvent", ar.class)}));
        a((c) new b(SingleWebView.class, true, new e[]{new e("onJsBroadcast", BroadcastMethod.a.class)}));
        a((c) new b(CaptchaLifeCycleObserver.class, true, new e[]{new e("onCaptchaConsumerEvent", com.ss.android.ugc.aweme.captcha.a.class)}));
        a((c) new b(RankingListActivity.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class)}));
        a((c) new b(com.ss.android.ugc.aweme.commercialize.log.x.class, true, new e[]{new e("onOperateEvent", com.ss.android.ugc.aweme.longvideo.a.a.class), new e("onVideoEvent", ar.class), new e("onCommentEvent", com.ss.android.ugc.aweme.comment.b.a.class), new e("onDestroyBreakEvent", com.ss.android.ugc.aweme.feed.f.h.class)}));
        a((c) new b(StaggeredNearByFragment.class, true, new e[]{new e("onNearbyTabRefreshEvent", y.class), new e("onChangeCityEvent", com.ss.android.ugc.aweme.feed.f.d.class), new e("onChangeNetwork", com.ss.android.ugc.aweme.qrcode.a.a.class)}));
        a((c) new b(TopPageAction.class, true, new e[]{new e("onEvent", AbsAdCardAction.b.class)}));
        e eVar9 = new e("onMusicCollectEvent", com.ss.android.ugc.aweme.music.a.e.class, ThreadMode.POSTING, 0, true);
        a((c) new b(NewMusicTabFragment.class, true, new e[]{eVar9}));
        a((c) new b(com.ss.android.ugc.aweme.newfollow.f.b.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.forward.c.a.class), new e("onPreloadEvent", com.ss.android.ugc.aweme.newfollow.c.d.class), new e("onUnFollowUserEvent", com.ss.android.ugc.aweme.newfollow.c.e.class), new e("onDeleteItemEvent", com.ss.android.ugc.aweme.newfollow.c.a.class), new e("onCommentDialogEvent", com.ss.android.ugc.aweme.feed.f.f.class), new e("onPrivateModelEvent", ad.class), new e("onCommentEvent", com.ss.android.ugc.aweme.comment.b.a.class), new e("onVideoEvent", ar.class), new e("onReportCommentEvent", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(HomeFragment.class, true, new e[]{new e("turnStoryPublish", com.ss.android.ugc.aweme.main.c.i.class), new e("closeStoryPublish", com.ss.android.ugc.aweme.main.c.a.class)}));
        a((c) new b(SearchResultFragment.class, true, new e[]{new e("onSearchCorrectEvent", com.ss.android.ugc.aweme.discover.a.e.class), new e("onGuideSearchEvent", com.ss.android.ugc.aweme.discover.a.a.class), new e("onInnerSearchEvent", com.ss.android.ugc.aweme.discover.a.b.class)}));
        a((c) new b(AbsAdCardAction.class, true, new e[]{new e("onEvent", AbsAdCardAction.d.class)}));
        a((c) new b(SettingAccountAndSafetyActivity.class, true, new e[]{new e("onBindMobileFinishEvent", com.ss.android.ugc.aweme.account.e.a.class)}));
        a((c) new b(AbsCellFeedFragmentPanel.class, true, new e[]{new e("onVideoEvent", ar.class)}));
        a((c) new b(com.ss.android.ugc.aweme.commerce.d.a.class, true, new e[]{new e("closeHalfDialog", CloseHalfDialogBridge.a.class, ThreadMode.MAIN)}));
        a((c) new b(SearchContainerFragment.class, true, new e[]{new e("onSearchViewAllEvent", com.ss.android.ugc.aweme.discover.a.h.class), new e("onSearchPreventSuicideEvent", SearchPreventSuicide.class)}));
        a((c) new b(bo.class, true, new e[]{new e("onEventDiggUpdate", z.class)}));
        e eVar10 = new e("onNetworkChanged", com.ss.android.ugc.aweme.qrcode.a.a.class, ThreadMode.POSTING, 1, false);
        a((c) new b(com.ss.android.ugc.aweme.freeflowcard.a.e.class, true, new e[]{eVar10}));
        a((c) new b(com.ss.android.ugc.aweme.rocket.e.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.rocket.b.class), new e("onEvent", com.ss.android.ugc.aweme.rocket.h.class)}));
        a((c) new b(com.ss.android.ugc.aweme.feed.ui.seekbar.detailvideo.b.class, true, new e[]{new e("onVideoProgressVolumeKeyEvent", g.class), new e("onPlayerControllerRenderFirstFrameEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.c.class), new e("onFullFeedVideoChangeEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.a.class), new e("onPlayerControllerVideoStatusEvent", com.ss.android.ugc.aweme.feed.ui.seekbar.e.class), new e("onPlayerControllerVideoPlayProgressChange", com.ss.android.ugc.aweme.feed.ui.seekbar.d.class)}));
        a((c) new b(AddChallengeFragment.class, true, new e[]{new e("onChallengeReadyEvent", com.ss.android.ugc.aweme.challenge.a.b.class)}));
        a((c) new b(com.ss.android.ugc.aweme.forward.d.n.class, true, new e[]{new e("onFollowFeedDetailEvent", com.ss.android.ugc.aweme.newfollow.c.b.class)}));
        a((c) new b(SettingNewVersionActivity.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class)}));
        a((c) new b(u.class, true, new e[]{new e("onEvent", com.bytedance.android.live.base.a.a.class)}));
        a((c) new b(AdFormMaskFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.commercialize.b.b.class), new e("onEvent", AbsAdCardAction.d.class), new e("onEvent", AbsAdCardAction.b.class)}));
        a((c) new b(MainFragment.class, true, new e[]{new e("onScrollToFeedFollowGuideEvent", com.ss.android.ugc.aweme.main.guide.d.class), new e("onHideUploadRecoverEvent", com.ss.android.ugc.aweme.shortvideo.f.d.class), new e("onPublishStatusUpdate", com.ss.android.ugc.aweme.shortvideo.f.e.class), new e("onSwipeRefreshInMainFragmentEvent", com.ss.android.ugc.aweme.main.c.g.class), new e("onMainSwipeRefreshABChangedEvent", com.ss.android.ugc.aweme.main.c.c.class), new e("onDislikeAwemeEvent", com.ss.android.ugc.aweme.feed.f.i.class), new e("onAwesomeSplashEvent", AwesomeSplashEvent.class), new e("onDismissSearchGuideEvent", l.class), new e("onLogoutEvent", com.ss.android.ugc.aweme.app.d.g.class), new e("onCaptchaConsumerEvent", com.ss.android.ugc.aweme.captcha.a.class), new e("onDismissTitleTabEvent", com.ss.android.ugc.aweme.feed.f.m.class), new e("onClickBottomTabEvent", com.ss.android.ugc.aweme.feed.f.e.class), new e("onChangeCityEvent", com.ss.android.ugc.aweme.feed.f.d.class), new e("onEnterHotSearchPageEvent", com.ss.android.ugc.aweme.feed.f.o.class), new e("onShowHotSearchGuideEvent", ao.class), new e("onAfterLoginInEvent", com.ss.android.ugc.aweme.login.a.a.class), new e("onLiveSquareGuideEvent", com.ss.android.ugc.aweme.feed.f.u.class), new e("onFeedsPageChangedEvent", r.class), new e("onCommerceDialogEvent", an.class), new e("onVideoPageChangeEvent", ac.class)}));
        a((c) new b(LiveBroadcastWarn.class, true, new e[]{new e("onCommentDialogEvent", com.ss.android.ugc.aweme.feed.f.f.class, ThreadMode.MAIN), new e("onBubbleGuideDismissEvent", com.ss.android.ugc.aweme.main.a.a.class, ThreadMode.MAIN), new e("onLiveTakeBubbleDismissEvent", com.ss.android.ugc.aweme.main.follow.f.class, ThreadMode.MAIN)}));
        a((c) new b(SummonFriendActivity.class, true, new e[]{new e("onSummonFriendClickEvent", com.ss.android.ugc.aweme.friends.a.b.class)}));
        a((c) new b(com.ss.android.ugc.aweme.newfollow.f.e.class, true, new e[]{new e("onHideUploadRecoverEvent", com.ss.android.ugc.aweme.shortvideo.f.d.class), new e("onLogoutEvent", com.ss.android.ugc.aweme.app.d.g.class), new e("onFollowStatusUpdate", FollowStatus.class)}));
        a((c) new b(LoginMethod.LoginProxyFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.login.a.b.class)}));
        a((c) new b(BizActivityViewModel.class, true, new e[]{new e("onEvent", com.bytedance.android.live.base.a.a.class)}));
        a((c) new b(StickersCollectListFragment.class, true, new e[]{new e("onStickerCollectEvent", com.ss.android.ugc.aweme.favorites.b.a.class)}));
        a((c) new b(com.ss.android.ugc.aweme.web.jsbridge.d.class, true, new e[]{new e("onBindMobileFinishEvent", com.ss.android.ugc.aweme.account.e.a.class)}));
        a((c) new b(com.ss.android.ugc.aweme.poi.ui.publish.a.class, true, new e[]{new e("onAsyncGoodsInfoEvent", com.ss.android.ugc.aweme.shortvideo.f.a.class)}));
        e eVar11 = new e("onMobMusicTypeEvent", com.ss.android.ugc.aweme.music.a.d.class, ThreadMode.POSTING, 0, true);
        e eVar12 = new e("onMusicCollectEvent", com.ss.android.ugc.aweme.music.a.e.class, ThreadMode.POSTING, 0, true);
        a((c) new b(MusicListFragment.class, true, new e[]{eVar11, eVar12}));
        a((c) new b(com.ss.android.ugc.aweme.web.jsbridge.c.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.web.jsbridge.t.class)}));
        a((c) new b(PortfolioActivity.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class)}));
        a((c) new b(Face2FaceAddFriendActivity.class, true, new e[]{new e("onNetStateChangeEvent", com.ss.android.ugc.aweme.qrcode.a.a.class)}));
        a((c) new b(NearByFragment.class, true, new e[]{new e("onNearbyTabRefreshEvent", y.class)}));
        a((c) new b(com.ss.android.ugc.aweme.feed.adapter.e.class, true, new e[]{new e("onFollowLiveStatusChange", com.bytedance.android.live.base.a.a.class)}));
        a((c) new b(FullScreenFollowFeedIn2TabFragment.class, true, new e[]{new e("onHideUploadRecoverEvent", com.ss.android.ugc.aweme.shortvideo.f.d.class), new e("onLogoutEvent", com.ss.android.ugc.aweme.app.d.g.class), new e("onPublishStatusUpdate", com.ss.android.ugc.aweme.shortvideo.f.e.class)}));
        a((c) new b(AdFormBrowserFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.commercialize.b.b.class), new e("onEvent", AbsAdCardAction.d.class), new e("onEvent", AbsAdCardAction.b.class)}));
        a((c) new b(POISearchDialog.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.poi.b.c.class)}));
        a((c) new b(InsFollowLiveViewHolderA.class, true, new e[]{new e("onFollowLiveStatusChange", com.bytedance.android.live.base.a.a.class), new e("onUnFollowUser", com.ss.android.ugc.aweme.newfollow.c.e.class)}));
        a((c) new b(com.ss.android.ugc.aweme.feed.adapter.g.class, true, new e[]{new e("onFollowLiveStatusChange", com.bytedance.android.live.base.a.a.class)}));
        a((c) new b(BaseDTProfileFragment.class, true, new e[]{new e("onDismissLike2DynamicGuideEvent", com.ss.android.ugc.aweme.profile.a.a.class)}));
        a((c) new b(ChooseMusicFragment.class, true, new e[]{new e("onSearchHistoryClick", com.ss.android.ugc.aweme.choosemusic.a.c.class)}));
        a((c) new b(com.ss.android.ugc.aweme.feed.panel.j.class, true, new e[]{new e("onMaskLayerCancelFollowEvent", com.ss.android.ugc.aweme.follow.b.a.class), new e("onFollowCleanModeChangedEvent", com.ss.android.ugc.aweme.main.b.b.class)}));
        a((c) new b(com.ss.android.ugc.aweme.commercialize.star.d.class, true, new e[]{new e("onJsBroacastReceiver", BroadcastMethod.a.class)}));
        a((c) new b(com.ss.android.ugc.aweme.newfollow.userstate.c.class, true, new e[]{new e("onVideoEvent", ar.class), new e("onEvent", com.ss.android.ugc.aweme.forward.c.a.class)}));
        a((c) new b(FeedFollowFragment.class, true, new e[]{new e("onVideoPublishEvent", ar.class), new e("onMaskLayerCancelFollowEvent", com.ss.android.ugc.aweme.follow.b.a.class)}));
        a((c) new b(CouponDetailActivity.class, true, new e[]{new e("onEvent", com.ss.android.websocket.b.b.c.class)}));
        a((c) new b(UserProfileFragment.class, true, new e[]{new e("onFakeCoverAction", com.ss.android.ugc.aweme.commercialize.b.h.class), new e("onCloseWebViewLoadingJsEvent", com.ss.android.ugc.aweme.commercialize.b.c.class), new e("onMobRequestIdEvent", com.ss.android.ugc.aweme.feed.f.x.class), new e("onEvent", com.ss.android.ugc.aweme.profile.a.b.class), new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class), new e("onEvent", com.ss.android.ugc.aweme.detail.ui.a.class), new e("onFollowStatusUpdate", FollowStatus.class, ThreadMode.MAIN), new e("onFeedAdClickFormEvent", com.ss.android.ugc.aweme.commercialize.b.e.class), new e("onFeedAdClickCouponEvent", com.ss.android.ugc.aweme.commercialize.b.d.class), new e("RefreshProfileAfterBlockEvent", com.ss.android.ugc.aweme.profile.a.f.class, ThreadMode.MAIN)}));
        a((c) new b(com.ss.android.ugc.aweme.notification.b.c.class, true, new e[]{new e("onAggregatedEvent", com.ss.android.ugc.aweme.notification.a.class), new e("onEvent", String.class, ThreadMode.MAIN)}));
        a((c) new b(LiveBroadcastAuthenticateActivity.class, true, new e[]{new e("onAuthenticationEvent", com.ss.android.ugc.aweme.fe.a.a.class, ThreadMode.MAIN)}));
        a((c) new b(NoOperateModeController.class, true, new e[]{new e("onOperateEvent", com.ss.android.ugc.aweme.longvideo.a.a.class)}));
        a((c) new b(HotSearchAndDiscoveryFragment2.class, true, new e[]{new e("onSearchResultOpenedEvent", com.ss.android.ugc.aweme.discover.a.g.class)}));
        a((c) new b(ProfileQuickShopContainer.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class)}));
        a((c) new b(com.ss.android.ugc.aweme.longvideonew.a.class, true, new e[]{new e("onCommentEvent", com.ss.android.ugc.aweme.comment.b.a.class), new e("onVideoEvent", ar.class)}));
        a((c) new b(FriendTabFragment.class, true, new e[]{new e("onNotificationIndicatorEvent", com.ss.android.ugc.aweme.message.b.c.class)}));
        a((c) new b(com.ss.android.ugc.aweme.longvideo.feature.NoOperateModeController.class, true, new e[]{new e("onOperateEvent", com.ss.android.ugc.aweme.longvideo.a.a.class)}));
        a((c) new b(SearchAwemeCardViewHolder.class, true, new e[]{new e("onVideoEvent", ar.class)}));
        a((c) new b(CollectMusicFragment.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.music.a.e.class)}));
        a((c) new b(PromoteProgramDialog.class, true, new e[]{new e("closeKrCopyright", com.ss.android.ugc.aweme.promote.c.class)}));
        a((c) new b(VideoCommentDialogFragment2.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.comment.b.b.class), new e("onEvent", com.ss.android.ugc.aweme.forward.c.a.class), new e("onEvent", com.ss.android.ugc.aweme.main.t.class), new e("onEvent", ah.class), new e("onAwesomeSplashEvent", AwesomeSplashEvent.class), new e("onReportCommentEvent", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(BottomFormDialogV2.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.commercialize.b.b.class)}));
        a((c) new b(FormAdCardAction.class, true, new e[]{new e("onEvent", AbsAdCardAction.b.class)}));
        a((c) new b(FollowVideoViewHolder.class, true, new e[]{new e("onFollowFeedDetailEvent", com.ss.android.ugc.aweme.newfollow.c.b.class)}));
        a((c) new b(TtAuthorizeActivity.class, true, new e[]{new e("onUpdateUserEvent", com.ss.android.ugc.aweme.base.a.b.class)}));
        a((c) new b(SlideSettingPageFragment.class, true, new e[]{new e("onEvent", TimeLockUserSetting.class, ThreadMode.MAIN)}));
        a((c) new b(MusicCollectListFragment.class, true, new e[]{new e("onMusicCollectEvent", com.ss.android.ugc.aweme.music.a.e.class)}));
        e eVar13 = new e("onDouyinPraiseFeedbackEvent", com.ss.android.ugc.aweme.ug.b.class, ThreadMode.POSTING, 0, true);
        a((c) new b(SubmitFeedbackActivity.class, true, new e[]{eVar13}));
        a((c) new b(PoiDetailActivity.class, true, new e[]{new e("onEvent", com.ss.android.ugc.aweme.poi.b.d.class)}));
        a((c) new b(ZhimaMethod.class, true, new e[]{new e("onVerifyEvent", com.ss.android.ugc.aweme.verify.a.class)}));
        a((c) new b(CommerceChallengeFragment.class, true, new e[]{new e("top", BroadcastMethod.a.class, ThreadMode.MAIN), new e("onJsBroadcast", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(MyProfileFragment.class, true, new e[]{new e("onFakeCoverAction", com.ss.android.ugc.aweme.commercialize.b.h.class), new e("onCloseWebViewLoadingJsEvent", com.ss.android.ugc.aweme.commercialize.b.c.class), new e("onDeleteAllStory", com.ss.android.ugc.aweme.story.api.a.a.class), new e("onFollowStatusUpdate", FollowStatus.class), new e("onSaveUserDataEvent", com.ss.android.ugc.aweme.profile.a.d.class), new e("onVideoEvent", ar.class, ThreadMode.MAIN), new e("onHidePerfectInfoGuideEvent", com.ss.android.ugc.aweme.profile.a.c.class), new e("onAuthRefreshEvent", com.ss.android.ugc.aweme.commerce.service.f.a.class), new e("onBindMobileFinishEvent", com.ss.android.ugc.aweme.account.e.a.class), new e("onUpdateUserEvent", com.ss.android.ugc.aweme.base.a.b.class), new e("onUpdateUserSuccessEvent", com.ss.android.ugc.aweme.base.a.c.class), new e("onLinkAuthSettingsFinishEvent", com.ss.android.ugc.aweme.commercialize.link.e.class), new e("onUpdateWhoCanSeeMyLikeListModeEvent", af.class, ThreadMode.MAIN), new e("onMyEnterpriseProfileEvent", com.ss.android.ugc.aweme.commercialize.b.g.class)}));
        a((c) new b(PublishSyncViewHolder.class, true, new e[]{new e("onPublishSyncEvent", com.ss.android.ugc.aweme.shortvideo.adapter.a.class)}));
        a((c) new b(com.ss.android.ugc.aweme.music.adapter.a.g.class, true, new e[]{new e("onSwitchMusicFragmentEvent", i.class)}));
        a((c) new b(com.ss.android.ugc.aweme.forward.d.k.class, true, new e[]{new e("onFollowFeedDetailEvent", com.ss.android.ugc.aweme.newfollow.c.b.class)}));
        e eVar14 = new e("onSettingSyncDone", com.ss.android.ugc.aweme.setting.a.d.class, ThreadMode.MAIN, 0, true);
        a((c) new b(com.ss.android.ugc.aweme.main.e.c.class, true, new e[]{eVar14}));
        a((c) new b(LoftView.class, true, new e[]{new e("onJsBroacastReceiver", BroadcastMethod.a.class, ThreadMode.MAIN)}));
        a((c) new b(FriendTabGuideDialogFragment.class, true, new e[]{new e("onScrollPublishEvent", com.ss.android.ugc.aweme.main.c.d.class)}));
        a((c) new b(com.ss.android.ugc.aweme.newfollow.f.f.class, true, new e[]{new e("onFollowFeedDetailEvent", com.ss.android.ugc.aweme.newfollow.c.b.class)}));
        a((c) new b(MusAbsProfileFragment.class, true, new e[]{new e("onUpdateWhoCanSeeMyLikeListModeEvent", af.class, ThreadMode.MAIN)}));
        a((c) new b(EventActivityComponent.class, true, new e[]{new e("onPublishStatus", com.ss.android.ugc.aweme.shortvideo.f.e.class), new e("onEvent", com.ss.android.ugc.aweme.festival.christmas.a.a.class, ThreadMode.MAIN)}));
        a((c) new b(com.ss.android.ugc.aweme.forward.d.a.class, true, new e[]{new e("onVideoEvent", ar.class)}));
        e eVar15 = new e("onToutiaoSettingDoneEvent", com.ss.android.ugc.aweme.antiaddic.b.c.class, ThreadMode.MAIN, 0, true);
        e eVar16 = new e("onPushSettingDone", com.ss.android.ugc.aweme.antiaddic.b.b.class, ThreadMode.MAIN, 0, true);
        a((c) new b(com.ss.android.ugc.aweme.main.e.d.class, true, new e[]{new e("onBroadCastEvent", BroadcastMethod.a.class, ThreadMode.MAIN), eVar15, eVar16, new e("onVideoPageChangeEvent", ac.class)}));
        a((c) new b(PreviewActivity.class, true, new e[]{new e("onEvent", ar.class), new e("onEvent", com.ss.android.ugc.aweme.im.service.model.g.class)}));
    }

    private static void a(c cVar) {
        c cVar2 = cVar;
        if (PatchProxy.isSupport(new Object[]{cVar2}, null, f50732a, true, 19498, new Class[]{c.class}, Void.TYPE)) {
            PatchProxy.accessDispatch(new Object[]{cVar2}, null, f50732a, true, 19498, new Class[]{c.class}, Void.TYPE);
            return;
        }
        f50733b.put(cVar.a(), cVar2);
    }

    public final c a(Class<?> cls) {
        Class<?> cls2 = cls;
        if (PatchProxy.isSupport(new Object[]{cls2}, this, f50732a, false, 19499, new Class[]{Class.class}, c.class)) {
            return (c) PatchProxy.accessDispatch(new Object[]{cls2}, this, f50732a, false, 19499, new Class[]{Class.class}, c.class);
        }
        c cVar = f50733b.get(cls2);
        if (cVar != null) {
            return cVar;
        }
        return null;
    }
}
